spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql:://localhost:3306/wizard_demo?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123456

server:
    port: 8081
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wizard.msg.dao